### ISSUE TITLE
add test code.

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#58]
## Todo
- [x] setting test environment
- [x] type test code in setting directory.
- [x] type test code in webview directory.
- [x] type test code in main.js.
- [x] add [CircleCI](https://circleci.com/) config.

**Comment by HyunmoAhn** [comment]
update Issue content because folder structure is changed by #78

**Comment by HyunmoAhn** [comment]
test coverage is 44% about `v.1.1.0` in #98

**Comment by HyunmoAhn** [comment]
Unit Test code is typed continuously. Close this issue.
