### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by HyunmoAhn** [AhKi/oh-my-desk#65]
# Todo

- [x] Category Of Action
- [x] Unify of Store
- [ ] Why Use Controller in Main process
- [ ] Command Script about `package.json`
- [ ] Project Folder Structure

> If need document, add above list

**Comment by HyunmoAhn** [comment]
Write [Category Of Action](https://github.com/AhKi/oh-my-desk/wiki/Category-of-Action) document

**Comment by HyunmoAhn** [comment]
Write [Unify of Store](https://github.com/AhKi/oh-my-desk/wiki/Unify-of-Store) document

**Comment by HyunmoAhn** [comment]
move this issue to #137. Because documentation is managed using [GitBook](https://gitbook.com)

close this issue.
